### ISSUE TITLE
Solving the assets path resolution maze

### ISSUE THREAD

**Issue by oncletom** [Mogztter/asciidoctor-pdf.js#48] opened 2019-05-02 14:12 UTC
We have different layers of assets:

- the ones relative to the template (JavaScript file)
- the ones relative to the document (and/or its `base-dir` attribute)
- the ones relative to the asciidoctor-pdf (embededd in the npm package)

The question is: what are the template assets relative to? The `base-dir`? The current working directory? The document?

**Comment by Mogztter** [comment] 2019-05-03 06:16
@matklad I'm wondering how to you handle paths in your template ? Do you use relative path ? Absolute path ? Do you embed the content of the external ressources ?

**Comment by matklad** [comment] 2019-05-03 07:46
In a pretty horrible way! For CSS, I use relative paths, and I copy-pasted `asciidoctor.css` alongside my own style. So I have this in html generated by template.js:

```
  <link href="../asciidoctor.css" rel="stylesheet">
  <link href="../slides.css" rel="stylesheet">
```

I also need a tiny bit of JS, and I embed it using this awful hack:


```
// template.js

module.exports = {
  document: (node) => {
    return `<!DOCTYPE html>
    ....
  <link href="../asciidoctor.css" rel="stylesheet">
  <link href="../slides.css" rel="stylesheet">
   ...
  <script>
  ${init.toString()} // 😨
  init()
  </script>
  ...
  `
  },
}

function init() {
  ...
}
```

**Comment by Mogztter** [comment] 2019-05-04 09:54
Thanks for sharing, it confirmed ours concerns 😅
I think the `asciidoctor.css` should be "globally available" somehow.

In my opinion, the most logical solution is to use paths relative to the template.
For instance:

```console
js/
  script.js
css/
  slides.css
template.js
```

```html
<link href="./css/slides.css" rel="stylesheet">
<script src="./js/script.js"></script>
```

Since we are using Node.js, we could use [`__dirname`](https://nodejs.org/api/modules.html#modules_dirname) to use absolute paths:

```js
const html = `
<link href="${__dirname}/css/slides.css" rel="stylesheet">
<script src="${__dirname}/js/script.js"></script>
`
```

Another idea is to provide an helper function to resolve resources.

```js
const html = `
<link href="${systemPath("./css/slides.css")}" rel="stylesheet">
<script src="${systemPath("./js/script.js")}"></script>
`
```

And if we combine this idea with the "globally available" `asciidoctor.css`:

```js
const html = `
<link href="${primaryStylesheetPath()}" rel="stylesheet">
<link href="${systemPath("./css/slides.css")}" rel="stylesheet">
<script src="${systemPath("./js/script.js")}"></script>
`
```

By default `systemPath` could resolve path relative to the template (using `__dirname`) but we could also accept a second argument to configure the "base directory".
For instance, if you define an `assetdir` in your document and you want to resolve the assets relative to this directory:

```js
const html = `
<link href="${primaryStylesheetPath()}" rel="stylesheet">
<link href="${systemPath('./css/slides.css', node.getAttribute('assetdir'))}" rel="stylesheet">
<script src="${systemPath('./js/script.js', node.getAttribute('assetdir'))}"></script>
`
```

We also thought about using a declarative approach where you must provide a list of stylesheets and a list of scripts but it might be too restrictive.

Another idea is to embed everything in the HTML page.
In my opinion, it has two advantages:

- The HTML page becomes portable (ie. you can copy this page on another machine)
- Chrome can be run in a sandboxed environment

To do that, we could declare assets like:

```js
${primaryStylesheet()}
${stylesheet('./css/slides.css')}
${script('./js/script.js')}
```

```html
<style>
  .content{}
  /* ... */
</style>
<style>
  .slides{}
  /* ... */
</style>
<script>
  console.log('hello')
  // ...
</script>
```

We could also provide function to read content:


```js
const html = `
<style>
  ${primaryStylesheetData()}
</style>
<style>
  ${data('./css/slides.css')}
</style>
<script>
  ${data('./js/script.js')}
</script>
`
```

For images:

```js
const html = `<img class="logo" src="${dataURI(systemPath('./img/logo.svg'))}"/>`
```

```html
<img class="logo" src="data:image/svg+xml;utf8,<svg ... > ... </svg>"/>
```

Just throwing some ideas... what do you think ?

**Comment by matklad** [comment] 2019-05-04 10:10
Don't have a strong opinion here, but I'd favor just embedding the stuff:

* portable HTML page is nice: you don't need a server for assets
* this simplifies live-reloading, as only HTML has to be watched by the browser, and the library will naturally know about all dependencies

The possible disadvantages are:

* things like jpeg images are not embeddable
* embedding big assets (lots of ccs, lots of js) in theory could make the stuff slower, especially if you have many documents that could share assets. In practice, I think the size should be small enough so that we don't need to worry about copy-pasting stuff several times

**Comment by djencks** [comment] 2019-12-31 04:05
Aren't "things like jpeg images" embeddable using data-uris? Pngs seem to work OK with asciidoctor 2.

**Comment by Mogztter** [comment] 2020-03-31 10:15
I think we now have a decent strategy.
I'm closing this issue but feel free to open a new one with a proposal on how to improve things further.

**Closed by Mogztter** 2020-03-31 10:15 UTC
